# Generated by Django 5.2.1 on 2025-06-09 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
