# Generated by Django 5.2.1 on 2025-06-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='external_company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
