# Generated by Django 5.2.1 on 2025-06-12 09:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_job_category_job_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('industry', models.CharField(blank=True, choices=[('technology', 'Technology'), ('education', 'Education'), ('healthcare', 'Healthcare'), ('manufacturing', 'Manufacturing'), ('construction', 'Construction'), ('retail', 'Retail'), ('transport', 'Transport & Logistics'), ('finance', 'Finance'), ('hospitality', 'Hospitality')], max_length=50, null=True)),
                ('low_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('average_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('high_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_type', models.CharField(choices=[('yearly', 'Per Year'), ('monthly', 'Per Month'), ('daily', 'Per Day'), ('hourly', 'Per Hour')], default='yearly', max_length=20)),
                ('overview', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
