# Generated by Django 5.2.1 on 2025-06-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_salaryreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryreport',
            name='industry',
        ),
        migrations.AddField(
            model_name='salaryreport',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='salary_reports', to='base.category'),
        ),
    ]
