# Generated by Django 5.2.1 on 2025-06-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_salaryreport_industry_salaryreport_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='salaryreport',
            name='company_name',
        ),
        migrations.AddField(
            model_name='salaryreport',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='salary_reports', to='base.salarycompany'),
        ),
    ]
