# Generated by Django 5.2.1 on 2025-06-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_salarycompany_remove_salaryreport_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryreport',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
