# Generated by Django 5.2.1 on 2025-06-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_salaryreport_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryreport',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
