# Generated by Django 5.2.1 on 2025-06-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_salaryrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryrequest',
            name='requests_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='salaryrequest',
            name='job_title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
