# Generated by Django 5.2.1 on 2025-06-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_salaryrequest_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryreport',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
