# Generated by Django 5.2.1 on 2025-06-12 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_salaryreport_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryreport',
            name='slug',
        ),
    ]
