# Generated by Django 5.2.1 on 2025-06-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_remove_salaryreport_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryreport',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
