# Generated by Django 5.2.1 on 2025-06-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_salaryreport_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobNotificationSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe_email', models.CharField(max_length=255)),
                ('notification_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='salaryreport',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
