# Generated by Django 5.2.1 on 2025-06-13 07:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_subject_pastpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastpaper',
            name='memo',
            field=models.FileField(default=django.utils.timezone.now, upload_to='exam_papers/memos/'),
            preserve_default=False,
        ),
    ]
