# Generated by Django 5.2.1 on 2025-06-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_pastpaper_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastpaper',
            name='file',
            field=models.FileField(upload_to='past_papers/questions/'),
        ),
        migrations.AlterField(
            model_name='pastpaper',
            name='memo',
            field=models.FileField(upload_to='past_papers/memos/'),
        ),
    ]
