# Generated by Django 5.2.1 on 2025-06-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_pastpaper_file_alter_pastpaper_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastpaper',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
