# Generated by Django 5.2.1 on 2025-06-13 09:46

import base.models
import ckeditor.fields
import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_pastpaper_download_count'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (max 100 characters)', max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier (auto-generated if blank)', max_length=120, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Article Category',
                'verbose_name_plural': 'Article Categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='base_articl_name_3eca68_idx'), models.Index(fields=['slug'], name='base_articl_slug_67859e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Article title (max 200 characters)', max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier (auto-generated if blank)', max_length=220, unique=True, verbose_name='Slug')),
                ('cover_image', models.ImageField(blank=True, help_text='Recommended size: 1200x630 pixels', null=True, upload_to=base.models.article_cover_upload_path, verbose_name='Cover Image')),
                ('content', ckeditor.fields.RichTextField(help_text='Main article content', verbose_name='Content')),
                ('excerpt', models.TextField(blank=True, help_text='Short summary for previews (max 300 characters)', max_length=300, verbose_name='Excerpt')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Publication status', max_length=10, verbose_name='Status')),
                ('is_featured', models.BooleanField(default=False, help_text='Mark as featured article', verbose_name='Featured')),
                ('published_at', models.DateTimeField(blank=True, help_text='Date when article was published', null=True, verbose_name='Published At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('view_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='View Count')),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (max 70 characters)', max_length=70, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, help_text='SEO description (max 160 characters)', max_length=160, verbose_name='Meta Description')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='Comma-separated tags for this article', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='base.articlecategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status'], name='base_articl_status_ceade8_idx'), models.Index(fields=['published_at'], name='base_articl_publish_5b75ec_idx'), models.Index(fields=['is_featured'], name='base_articl_is_feat_558f44_idx'), models.Index(fields=['slug'], name='base_articl_slug_2baec4_idx')],
            },
        ),
    ]
