# Generated by Django 5.2.1 on 2025-06-13 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_articlecategory_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bursary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the official name of the bursary or funding opportunity.', max_length=200, unique=True, verbose_name='Bursary Title')),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from the title', max_length=220, unique=True)),
                ('provider', models.CharField(help_text='Organization or institution offering this bursary', max_length=150, verbose_name='Provider')),
                ('description', models.TextField(help_text='Brief details about the bursary or funding', verbose_name='Description')),
                ('eligibility', models.TextField(blank=True, help_text='Who can apply for this bursary', verbose_name='Eligibility Requirements')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Application Deadline')),
                ('website_link', models.URLField(blank=True, help_text='Official website or application page', null=True, verbose_name='Provider Website Link')),
                ('application_pdf', models.FileField(blank=True, help_text='Optional brochure or application form in PDF format', null=True, upload_to='bursaries/pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Downloadable PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bursary or Funding Opportunity',
                'verbose_name_plural': 'Bursaries & Funding',
                'ordering': ['-deadline', 'title'],
            },
        ),
    ]
