# Generated by Django 5.2.1 on 2025-06-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_bursary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('provider', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('link', models.URLField(verbose_name='External Link')),
                ('image', models.ImageField(blank=True, null=True, upload_to='certifications/')),
                ('price_type', models.CharField(choices=[('FREE', 'Free'), ('PAID', 'Paid')], default='FREE', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('students_enrolled', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
