# Generated by Django 5.2.1 on 2025-06-19 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='base.category')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='base.subcategory'),
        ),
    ]
