# Generated by Django 5.2.1 on 2025-06-19 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_subcategory_job_subcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2025, 12, 16, 11, 49, 55, 137040, tzinfo=datetime.timezone.utc)),
        ),
    ]
