# Generated by Django 5.2.1 on 2025-06-20 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_job_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2025, 12, 17, 12, 52, 52, 763288, tzinfo=datetime.timezone.utc)),
        ),
    ]
