# Generated by Django 5.2.1 on 2025-06-23 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_alter_job_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2025, 12, 20, 7, 17, 19, 151373, tzinfo=datetime.timezone.utc)),
        ),
    ]
