# Generated by Django 5.2.1 on 2025-07-01 08:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_university_acronym_alter_job_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='base.companyprofile'),
        ),
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2025, 12, 28, 8, 51, 51, 467270, tzinfo=datetime.timezone.utc)),
        ),
    ]
