# Generated by Django 5.2.1 on 2025-07-01 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_remove_companyprofile_user_user_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2025, 12, 28, 8, 58, 3, 804952, tzinfo=datetime.timezone.utc)),
        ),
    ]
