# Generated by Django 5.2.1 on 2025-07-01 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_alter_job_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2025, 12, 28, 8, 59, 19, 431905, tzinfo=datetime.timezone.utc)),
        ),
    ]
