# Generated by Django 5.2.1 on 2025-07-03 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_alter_job_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2025, 12, 30, 7, 1, 20, 916593, tzinfo=datetime.timezone.utc)),
        ),
    ]
