# Generated by Django 5.2.1 on 2025-07-02 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_alter_job_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('candidate', 'Candidate'), ('employer', 'Employer')], default='candidate', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2025, 12, 29, 7, 40, 45, 816250, tzinfo=datetime.timezone.utc)),
        ),
    ]
