# Generated by Django 5.2.1 on 2025-07-02 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_user_user_type_alter_job_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2025, 12, 29, 9, 39, 45, 167577, tzinfo=datetime.timezone.utc)),
        ),
    ]
