# Generated by Django 5.2.1 on 2025-07-02 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_alter_job_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2025, 12, 29, 9, 49, 41, 341184, tzinfo=datetime.timezone.utc)),
        ),
    ]
