# Generated by Django 5.2.1 on 2025-07-04 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_alter_job_deadline_alter_job_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2025, 12, 31, 7, 33, 4, 341708, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full Time (Permanent)'), ('part_time', 'Part Time'), ('fixed_term', 'Fixed Term Contract'), ('contract', 'Independent Contractor'), ('freelance', 'Freelance'), ('internship', 'Internship'), ('learnership', 'Learnership (NQF-aligned)'), ('apprentice', 'Apprenticeship'), ('trainee', 'Trainee'), ('remote', 'Remote Work'), ('hybrid', 'Hybrid Work'), ('seasonal', 'Seasonal Work'), ('casual', 'Casual Work'), ('volunteer', 'Volunteer'), ('epwp', 'EPWP (Expanded Public Works Programme)'), ('yes', 'YES (Youth Employment Service)')], max_length=20, null=True),
        ),
    ]
