# Generated by Django 5.2.1 on 2025-07-04 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_alter_job_deadline_alter_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2025, 12, 31, 7, 36, 44, 553591, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='job',
            name='internal_or_external',
            field=models.CharField(choices=[('external', 'External'), ('internal', 'Internal')], default='internal', max_length=10),
        ),
    ]
