# Generated by Django 5.2.1 on 2025-07-04 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_alter_job_deadline_alter_job_internal_or_external'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2025, 12, 31, 7, 36, 52, 931115, tzinfo=datetime.timezone.utc)),
        ),
    ]
